### ISSUE TITLE
Cursor is tiny hovering over Granite apps with a HiDPI display

### ISSUE THREAD

**Issue by DougBeney** [elementary/granite#231] opened 2018-10-24 18:13 UTC
On a HiDPI/Retina display, the mouse cursor will get tiny hovering over Granite apps.
If you hover over a regular GTK/Qt app, the proper cursor size is displayed.

[Here is a video that demonstrates this](https://www.youtube.com/watch?v=-pzz_v10Ve4&feature=youtu.be).

I have tried [editing the gsettings](https://elementaryos.stackexchange.com/questions/2762/mouse-cursor-size) with no success. (Had no effect on anything)

**Comment by danrabbit** [comment] 2018-10-25 18:07
Granite.Application is deprecated and I believe we've finished migrating all of our apps from it. Even Granite Widgets are just using regular Gtk. I can reproduce this issue with Epiphany which is not using Granite.Appliaction or any Granite widgets. So I think this is probably more likely an issue somewhere else in the stack.

I'm going to close this as "Out of scope" since it seems it's not actually an issue with Granite. It might be an issue with Gtk+, Gala, or somewhere else along the line

**Closed by danrabbit** 2018-10-25 18:07 UTC

**Comment by DougBeney** [comment] 2018-10-25 18:44
Interesting. Any idea if there are any other places I should post this issue?
