### ISSUE TITLE
Expand tab width to fill tab bar

### ISSUE THREAD

**Issue by D0J0P** [elementary/granite#239] opened 2018-10-18 15:09 UTC
I started a [post](https://plus.google.com/photos/photo/104362843500611550798/6613365928764600546?sqid=104613975513761463450&ssid=f519a7cd-31d2-4c2a-a6a1-f3bb617eb0fd) on elementary's Google+ page after playing with dconf settings for Epiphany, and found I could expand the tab width to fill the tab bar. Here's some points I made in the conversation: 

"+Cassidy James Blaede Other than Grzegorz G.'s suggestion to wait until the mouse is off the tab bar to change width, there's also the way Mac OS does it here: [youtube.com - Use Tabs in macOS Sierra](https://www.youtube.com/watch?v=3jzb4FtVulo)

You can see there's a moment when he closed a tab, the close button for the next one landed where his mouse was. During this time, I'm sure he could have closed the next tab. Doing things this way keeps all the functionality. So we don't have to do it the exact way Epiphany does it, but we can do it in a way that doesn't make closing lots of tabs rapidly any worse. "
...
"It would even give a potential affordance. By keeping the tabs at the same minimum width when you have a lot of them, it doesn't make the tab description any shorter. When you have less tabs, however, you can read more of the tab description."

Can we make this the new look for tabs bar in elementary?

**Comment by andreasfelix** [comment] 2019-07-04 21:25
Expanding the tabs to fill the tab-bar would remove the functionality to create a new tab (restore the last closed tab) when double-clicking (middle/three-finger clicking) on an empty part of tab-bar.

But this would also solve #221, which is caused by the event propagation of the `button_press_event` from the left/right arrows to the dynamic notebook.

As the post is no longer available, I made two screenshots:
![Filled_tabs_dark](https://user-images.githubusercontent.com/24651767/60687821-51c86b80-9eb1-11e9-941c-90dad6b54714.jpeg)
![Filled tabs](https://user-images.githubusercontent.com/24651767/60687819-51c86b80-9eb1-11e9-80da-ec5a6866af50.jpeg)

**Comment by andreasfelix** [comment] 2019-07-05 02:06
![filled](https://user-images.githubusercontent.com/24651767/60693289-0c6c6400-9eda-11e9-811a-a9077e7f43f8.gif)


I did a first implementation of a tab-bar with filled tabs. Similar to macOS/Chrome the tabs keep their witdh until the cursor leaves the tab-bar, which is convenient when rapidly closing multiple tabs.

**Comment by jlnr** [comment] 2019-07-06 13:49
@andreasfelix I think this looks really good! Please do send a PR :)

**Comment by D0J0P** [comment] 2019-07-09 23:40
Looks good! A few things:

Tabs don't seem to end just before the history button in the granite demo like they do in your earlier picture of the terminal. Hopefully they will behave like the terminal, for more real estate and it looks nicer.

Are there gonna be animations for tabs opening, closing and resizing?

**Comment by andreasfelix** [comment] 2019-07-10 11:28
As you can see in the PR the tabs will now fill the entire tab-bar (like first screenshot)!

Animations would be nice, but I am not sure how to do this. Maybe someone can help?

**Comment by jlnr** [comment] 2019-07-20 16:41
I have poked the UX folks about this since we now have an implemention in #302. The consensus seems to be that the initial tab width should be wider than it is now, but unconditionally filling 100% of the tab bar is too much. When a single tab gets too wide, it is not recognizable as a tab anymore, and we lose the affordance.

I'll go ahead and close this ticket, since the other feature in the issue description already exists as #17. If you think that there are other aspects of macOS tabs that should be considered for Granite, please open separate issues. Thanks and sorry for shooting this down! :pray:

**Closed by jlnr** 2019-07-20 16:41 UTC
