### ISSUE TITLE
Relocate the "New Tab" button to the end

### ISSUE THREAD

**Issue by KomradBear** [elementary/granite#413] opened 2020-07-27 10:49 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
The behavior of creating new tabs from the left side is extremely confusing for users on any Left-To-Right UI based language, it would make sense for a Right-To-Left UI to have the + sign from the left of the tabs but it makes zero sense for Left-To-Right languages. Starting a new tab before the current working tab seems like a design mistake.

I should also add that I often times clicked the X to close to tab by mistake when trying to open a new tab.

**Describe the solution you'd like**
Please consider relocating the + ("new tab") sign to the right side of the tabs for Left-To-Right UI.

![Screen Shot 2020-07-27 at 13 33 46](https://user-images.githubusercontent.com/68272253/88533319-c61b0300-d00e-11ea-9c19-cf1a12a33609.png)

**Existing work**
Every single software made for UI on Left-To-Right languages uses the + from the right of the tab, an example is Finder in macOS, or any web browser, or any tab based software in existence.

![Screen Shot 2020-07-27 at 13 47 19](https://user-images.githubusercontent.com/68272253/88533919-b4862b00-d00f-11ea-88e8-880cc452f4ad.png)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by dar5hak** [comment] 2020-08-28 17:22
It's interesting that even macOS puts the new tab button to the right even though they generally have close buttons on the left. Probably because right is where the newly opened tab is going to show up?

**Comment by DisguisedBear** [comment] 2020-09-11 13:47
> Probably because right is where the newly opened tab is going to show up?

It doesn't really matter in terms of position, the issue is that it doesn't feel "natural".
If we're talking about RTL languages then it makes sense for the new tab button to be on the right, if its LTR then the exact opposite is true.

**Comment by cassidyjames** [comment] 2020-10-09 20:23
Personally, I'm kind of indifferent regarding the location of the `+` button. And to be clear, the left-to-right versus right-to-left language issue is a non-issue as the button goes to the "start" of the widget, which is handled by GTK. But for start vs. end, I understand both arguments:

- **Start**: It's an important control and the only notebook-wide action, so we put it at the start. This is consistent with toolbar actions. A downside is that this is inconsistent with other platforms.
- **End**: It's a contextual control, and notebook tabs show up at the end of the existing tabs, so put it at the end. A downside is that this means the button moves around, unless we do full-width tabs (like GNOME and macOS).

Given this, I am leaning toward moving it to the end, after the last tab (similar to Chrome and Firefox). This is probably the most familiar to users, and I do like the more contextual nature of it. But I don't feel _super_ strongly, and would invite further feedback from @elementary/ux.

**Comment by danrabbit** [comment] 2020-10-09 22:31
In my personal usage, I always double click the blank space in the tab bar.

Having a non moving button is good if you want to say open 5 tabs in a row, but I have no idea why you'd want to do that

It would probably be fine to have the button in the position where the next tab would go as in Chrome/Firefox etc. I think the way Gtk notebook is set up, it's a lot easier to add action buttons on either side

Realistically, I can see Granite.DynamicNotebook being deprecated for the new tab bar Alex is working on anyways, so I'm not sure it's super worth putting a lot of effort here when we'll likely just go with what they do

**Comment by cassidyjames** [comment] 2020-11-04 19:55
@Exalm so I guess consider this as a little more freedom in the design of that new tab bar? :smile: I do think for non-full-width tabs that just going with immediately-after the last tab will be the most familiar. It's also what MS Edge (now the 2nd-most used browser) does. :stuck_out_tongue:

**Comment by Exalm** [comment] 2020-11-05 07:09
Right now it's not possible in either, but I can look at making it possible for HdyTabBar when the time comes to finish it up. :)

**Comment by hanaral** [comment] 2021-03-11 12:45
I think it may just be helpful to leave the button as is and add a hover tooltip to the blank space that says
```
Open new tab 
[Double click]
```

**Comment by jeremypw** [comment] 2021-03-11 13:48
:+1: for the tooltip - I was not aware of that feature.

**Comment by Gj8x3GK5ev** [comment] 2021-03-11 14:02
> I think it may just be helpful to leave the button as is and add a hover tooltip to the blank space that says
> 
> ```
> Open new tab 
> [Double click]
> ```

The issue is that often times when I'm going for the new tab button, I accidentally click the close button if the first tab is selected.
I don't think I'm the only one who had this happen to himself... its really annoying when I accidentally close the file browser or the first tab. The proximity of those two icons is too close which is a design flaw.

I doubt just adding a tool tip will solve this issue because I personally never double click the tabs bar to open a new tab, I'm one of those who actually uses the button.

**Comment by jeremypw** [comment] 2021-03-11 16:08
@Gj8x3GK5ev I tend to agree. The tooltip should be in addition to any other solution. But if, as Dan said, the Granite.DynamicNotebook is on its way out, there does not seem to be much appetite to change it. However, I'll have a look to see if the fix is straightforward and maybe propose something.

**Comment by danrabbit** [comment] 2022-04-14 19:29
Closing since we removed DynamicNotebook in favor of Hdy.Tabbar

**Closed by danrabbit** 2022-04-14 19:29 UTC
Labels: Needs Design
